### ISSUE TITLE
Add maven-jpackage-template

### ISSUE THREAD

**Issue by wiverson** [mhrimaz/AwesomeJavaFX#101]
https://github.com/wiverson/maven-jpackage-template

Template showing how to build JavaFX desktop apps with small jlink JVMs using just Maven (no shell scripts needed). Includes GitHub Actions showing how to build macOS, Windows, and Linux installer packages automatically.

LMK if you prefer a PR, not sure if this is easier?

**Comment by AlmasB** [comment]
Thanks for this, a PR would be helpful, yeah

**Comment by wiverson** [comment]
Just sent PR https://github.com/mhrimaz/AwesomeJavaFX/pull/104 - LMK if that works. :)

**Comment by AlmasB** [comment]
All merged
