### ISSUE TITLE
Is there any library for reports?

### ISSUE THREAD

**Issue by ahmeedev** [mhrimaz/AwesomeJavaFX#108]

**Comment by Hakky54** [comment]
What kind of reporting you mean?

**Comment by Hakky54** [comment]
Closing this issue as there is no response

**Comment by ctoabidmaqbool1** [comment]
I you was saying about pdf reports then some options:
* https://github.com/itext/itextpdf
* https://github.com/itext/itext-java
* https://github.com/LibrePDF/OpenPDF
* https://github.com/apache/pdfbox
