### ISSUE TITLE
Are there any Gitter/Slack/Discord groups concerning general JavaFX desktop development?

### ISSUE THREAD

**Issue by valnaumov** [mhrimaz/AwesomeJavaFX#130]
I feel a need to chat with the people in my field (JavaFX desktop development), but could not find any groups

**Comment by salmonb** [comment]
I have a Discord channel for WebFX, you will find the link in [README](https://github.com/webfx-project/webfx). It's normally more for the WebFX support, but you can also ask questions about JavaFX in general.

**Comment by valnaumov** [comment]
@salmonb Discord says this https://discord.com/invite/9sUeggb6 invitation is expired.

**Comment by salmonb** [comment]
@valnaumov I updated the link to https://discord.gg/b8s5RWR9 and asked Discord to set this link to never expire (I thought I already dit it on the previous link but maybe not).

**Comment by Hakky54** [comment]
It seems like OP gave a thumps up to the option of Salmonb, so I am closing this issue
