### ISSUE TITLE
Change License

### ISSUE THREAD

**Issue by LeFryskai** [mhrimaz/AwesomeJavaFX#27]
> has an appropriate license (Meaning something like CC0, NOT a code licence like MIT, BSD, Apache, etc) (If you use a license badge, it should be SVG, not PNG)

The license need to be change to be in the general Awesome List

**Comment by mhrimaz** [comment]
Not sure what licence i should use, but i changed it.

**Comment by LeFryskai** [comment]
The license is always a complicated thing.
I gonna ask if everything is correct.
