### ISSUE TITLE
Recommendation for Project

### ISSUE THREAD

**Issue by goxr3plus** [mhrimaz/AwesomeJavaFX#32]
Hello mhrimaz :)

Can you add XR3Player (  https://github.com/goxr3plus/XR3Player ) on the JavaFX projects that you have on your read me list ? i would be extra glad if you do .
Best Regards Alex K.

**Comment by mhrimaz** [comment]
Happy to share. Please help to make this awesome list more awesome.
Good Luck

**Comment by goxr3plus** [comment]
😊

Στις 18 Ιουν 2017 12:55 μ.μ., ο χρήστης "Hossein Rimaz" <
notifications@github.com> έγραψε:
