### ISSUE TITLE
FXForm2

### ISSUE THREAD

**Issue by amischler** [mhrimaz/AwesomeJavaFX#36]
Hello,

Could you consider adding FXForm2 (http://dooapp.github.io/FXForm2/) to your list ? I hope that this could be useful to others.

Disclaimer : I'm the lead developer ;)

**Comment by mhrimaz** [comment]
if this project is actively evolving then yes it will be on the list. please submit a pull request

**Comment by amischler** [comment]
Thanks for your answer, PR submitted.
