### ISSUE TITLE
Add FX-BorderlessScene in list of Libraries :) 

### ISSUE THREAD

**Issue by goxr3plus** [mhrimaz/AwesomeJavaFX#44]
This period i have developed a very powerful library for creating undecorated JavaFX Stages with the following characteristics:

**Undecorated JavaFX Scene with implemented move, resize, minimise, maximise, close and Windows Aero Snap controls.** 

Its 2 good classes and very very useful :). 

The Project URL :

https://github.com/goxr3plus/FX-BorderlessScene

**Comment by mhrimaz** [comment]
please submit a pull request

**Comment by goxr3plus** [comment]
@mhrimaz  Here we go :) Added FX-BorderlessScene on JavaFX Libraries #55
