### ISSUE TITLE
TiwulFX

### ISSUE THREAD

**Issue by jingglang** [mhrimaz/AwesomeJavaFX#66]
Hi,

Could you please include TiwulFX library to the list?

https://bitbucket.org/panemu/tiwulfx

Thank you,

**Comment by mhrimaz** [comment]
Hi,

It's an awesome project but why it is hosted on bitbucket? 

It would be much better to host it on GitHub, though please submit a pull request in order to include it in the list.

Regards.

**Comment by jingglang** [comment]
Hi @mhrimaz ,

I've created the pull request.
There is no particular reason about hosting on bitbucket. Care to share why it is a problem?

Thank you,
